<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <RootNamespace>KS_Signage.Issuer</RootNamespace>
    <AssemblyName>KS_Signage.Issuer</AssemblyName>
    <StartupObject>KS_Signage.Issuer.Program</StartupObject>
    <EnableDefaultApplicationDefinition>false</EnableDefaultApplicationDefinition>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\KS_Signage.Licensing\KS_Signage.Licensing.csproj" />
  </ItemGroup>

</Project>
