<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>PdfSignage.Issuer</RootNamespace>
    <AssemblyName>PdfSignage.Issuer</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\PdfSignage.Licensing\PdfSignage.Licensing.csproj" />
  </ItemGroup>

</Project>
